// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MusiqueStream;

public interface GestionMusiqueStreamPrx extends Ice.ObjectPrx
{
    public String Stream(String command, String musique);

    public String Stream(String command, String musique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Stream(String command, String musique);

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Stream(String command, String musique, Ice.Callback __cb);

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_Stream(String command, String musique, Callback_GestionMusiqueStream_Stream __cb);

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx, Callback_GestionMusiqueStream_Stream __cb);

    public String end_Stream(Ice.AsyncResult __result);

    public void Delete(String musique);

    public void Delete(String musique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Delete(String musique);

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Delete(String musique, Ice.Callback __cb);

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_Delete(String musique, Callback_GestionMusiqueStream_Delete __cb);

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx, Callback_GestionMusiqueStream_Delete __cb);

    public void end_Delete(Ice.AsyncResult __result);
}
