// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.sample.MusiqueStream;

public final class GestionMusiqueStreamPrxHelper extends Ice.ObjectPrxHelperBase implements GestionMusiqueStreamPrx
{
    private static final String __Delete_name = "Delete";

    public void Delete(String musique)
    {
        Delete(musique, null, false);
    }

    public void Delete(String musique, java.util.Map<String, String> __ctx)
    {
        Delete(musique, __ctx, true);
    }

    private void Delete(String musique, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "Delete", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _GestionMusiqueStreamDel __del = (_GestionMusiqueStreamDel)__delBase;
                    __del.Delete(musique, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_Delete(String musique)
    {
        return begin_Delete(musique, null, false, null);
    }

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx)
    {
        return begin_Delete(musique, __ctx, true, null);
    }

    public Ice.AsyncResult begin_Delete(String musique, Ice.Callback __cb)
    {
        return begin_Delete(musique, null, false, __cb);
    }

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_Delete(musique, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_Delete(String musique, Callback_GestionMusiqueStream_Delete __cb)
    {
        return begin_Delete(musique, null, false, __cb);
    }

    public Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx, Callback_GestionMusiqueStream_Delete __cb)
    {
        return begin_Delete(musique, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_Delete(String musique, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __Delete_name, __cb);
        try
        {
            __result.__prepare(__Delete_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(musique);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_Delete(Ice.AsyncResult __result)
    {
        __end(__result, __Delete_name);
    }

    private static final String __Stream_name = "Stream";

    public String Stream(String command, String musique)
    {
        return Stream(command, musique, null, false);
    }

    public String Stream(String command, String musique, java.util.Map<String, String> __ctx)
    {
        return Stream(command, musique, __ctx, true);
    }

    private String Stream(String command, String musique, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "Stream", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("Stream");
                    __delBase = __getDelegate(false);
                    _GestionMusiqueStreamDel __del = (_GestionMusiqueStreamDel)__delBase;
                    return __del.Stream(command, musique, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_Stream(String command, String musique)
    {
        return begin_Stream(command, musique, null, false, null);
    }

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx)
    {
        return begin_Stream(command, musique, __ctx, true, null);
    }

    public Ice.AsyncResult begin_Stream(String command, String musique, Ice.Callback __cb)
    {
        return begin_Stream(command, musique, null, false, __cb);
    }

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_Stream(command, musique, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_Stream(String command, String musique, Callback_GestionMusiqueStream_Stream __cb)
    {
        return begin_Stream(command, musique, null, false, __cb);
    }

    public Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx, Callback_GestionMusiqueStream_Stream __cb)
    {
        return begin_Stream(command, musique, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_Stream(String command, String musique, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__Stream_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __Stream_name, __cb);
        try
        {
            __result.__prepare(__Stream_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(command);
            __os.writeString(musique);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public String end_Stream(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __Stream_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static GestionMusiqueStreamPrx checkedCast(Ice.ObjectPrx __obj)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GestionMusiqueStreamPrx)
            {
                __d = (GestionMusiqueStreamPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GestionMusiqueStreamPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GestionMusiqueStreamPrx)
            {
                __d = (GestionMusiqueStreamPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GestionMusiqueStreamPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GestionMusiqueStreamPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GestionMusiqueStreamPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GestionMusiqueStreamPrx)
            {
                __d = (GestionMusiqueStreamPrx)__obj;
            }
            else
            {
                GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static GestionMusiqueStreamPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GestionMusiqueStreamPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            GestionMusiqueStreamPrxHelper __h = new GestionMusiqueStreamPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::MusiqueStream::GestionMusiqueStream"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _GestionMusiqueStreamDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _GestionMusiqueStreamDelD();
    }

    public static void __write(IceInternal.BasicStream __os, GestionMusiqueStreamPrx v)
    {
        __os.writeProxy(v);
    }

    public static GestionMusiqueStreamPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            GestionMusiqueStreamPrxHelper result = new GestionMusiqueStreamPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
